---
detectors:
  NilCheck:
    enabled: false
  TooManyStatements:
    enabled: false
  DataClump:
    enabled: false
  LongParameterList:
    max_params: 5
  DuplicateMethodCall:
    allow_calls:
      - 'format.*'
      - 'where.*'
      - 'default_columns'
      - 'references'

exclude_paths:
  - node_modules
  - vendor

directories:
  'app/reflexes':
    IrresponsibleModule:
      enabled: false
  'app/components':
    TooManyInstanceVariables:
      enabled: false
    BooleanParameter:
      enabled: false
    IrresponsibleModule:
      enabled: false
    LongParameterList:
      enabled: false
  'app/lib':
    IrresponsibleModule:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  'app/jobs':
    IrresponsibleModule:
      enabled: false
  'app/channels':
    IrresponsibleModule:
      enabled: false
  'test':
    IrresponsibleModule:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  'db':
    IrresponsibleModule:
      enabled: false
    DuplicateMethodCall:
      enabled: false
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  'app/controllers':
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  'app/helpers':
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  'app/mailers':
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
  'app/models':
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
